---
name: Buildings
export_to:
carrier: electricity
behavior: base_load_buildings
visible: true
composite: false
default_capacity:
default_volume:
default_demand:
default_position_relative_to_buffer:
expandable: true
importable_attributes: []
technology_component_behavior:
  flex: optional
  inflex: generic
