---
name: Household aggregated
export_to:
carrier: electricity
behavior: optional
visible: false
composite: false
default_capacity:
default_volume:
default_demand:
default_position_relative_to_buffer:
expandable: true
importable_attributes: []
technology_component_behavior:
  flex: optional
  inflex: generic
