---
name: Buffer space heating
export_to:
carrier: electricity
behavior:
visible: true
composite: true
default_capacity: 10.0
default_volume: 2.9065
default_demand:
default_position_relative_to_buffer:
expandable: true
importable_attributes: []
technologies:
- households_space_heater_heatpump_air_water_electricity
- households_space_heater_heatpump_ground_water_electricity
- households_space_heater_network_gas
- households_space_heater_combined_network_gas
- households_space_heater_hybrid_heatpump_air_water_electricity_gas
- households_space_heater_hybrid_heatpump_air_water_electricity_electricity
