---
name: Neighbourhood battery
export_to:
carrier: electricity
behavior: congestion_battery
visible: true
composite: false
default_capacity: 10.0
default_volume: 100.0
default_demand:
default_position_relative_to_buffer:
expandable: true
profile_required: false
importable_attributes: []
