---
name: Power-To-Gas
export_to: number_of_energy_flexibility_p2g_electricity
carrier: electricity
behavior: siphon
visible: true
composite: false
default_capacity: 739.583
default_volume:
default_demand:
default_position_relative_to_buffer:
expandable: true
profile_required: false
importable_attributes:
- fixed_operation_and_maintenance_costs_per_year
- full_load_hours
- initial_investment
- input_capacity
- technical_lifetime
- variable_operation_and_maintenance_costs_for_ccs_per_full_load_hour
- variable_operation_and_maintenance_costs_per_full_load_hour
