---
name: Other
export_to: 
carrier: electricity
behavior: 
visible: true
composite: false
default_capacity: 
default_volume: 
default_demand: 
default_position_relative_to_buffer: 
expandable: true
importable_attributes: []
