---
name: Hybrid heat pump space heating (electricity)
export_to: 
carrier: electricity
behavior: hhp_electricity
visible: true
composite: false
default_capacity: 1.08889
default_volume: 
default_demand: 
default_position_relative_to_buffer: buffering
expandable: true
importable_attributes: []
