---
name: Households space heater combined network gas
export_to: 
carrier: gas
behavior: 
visible: true
composite: false
default_capacity: 20.6186
default_volume: 
default_demand: 
default_position_relative_to_buffer: boosting
expandable: true
importable_attributes:
- initial_investment
- input_capacity
- storage.volume
- technical_lifetime
- variable_operation_and_maintenance_costs_for_ccs_per_full_load_hour
- variable_operation_and_maintenance_costs_per_full_load_hour
