---
name: Heat pump for space heating (air)
export_to: households_space_heater_heatpump_air_water_electricity_share
carrier: electricity
behavior: buffer
visible: true
composite: false
default_capacity: 2.22222
default_volume: 
default_demand: 
default_position_relative_to_buffer: buffering
expandable: true
importable_attributes:
- coefficient_of_performance
- fixed_operation_and_maintenance_costs_per_year
- full_load_hours
- initial_investment
- input_capacity
- technical_lifetime
- variable_operation_and_maintenance_costs_for_ccs_per_full_load_hour
- variable_operation_and_maintenance_costs_per_full_load_hour
