---
name: Hybrid heat pump space heating (gas)
export_to: 
carrier: gas
behavior: hhp_gas
visible: true
composite: false
default_capacity: 20.6186
default_volume: 
default_demand: 
default_position_relative_to_buffer: boosting
expandable: true
importable_attributes: []
