---
name: Households water heater network gas
export_to: 
carrier: gas
behavior: 
visible: true
composite: false
default_capacity: 35.8209
default_volume: 
default_demand: 
default_position_relative_to_buffer: boosting
expandable: true
importable_attributes: []
