---
name: Households water heater fuel cell chp network gas
export_to: 
carrier: gas
behavior: 
visible: false
composite: false
default_capacity: 
default_volume: 
default_demand: 
default_position_relative_to_buffer: 
expandable: true
importable_attributes: []
