---
name: Power-To-Heat
export_to: households_flexibility_p2h_electricity_market_penetration
carrier: electricity
behavior: optional_buffer
visible: true
composite: false
default_capacity: 2.0
default_volume: 9.3
default_demand: 
default_position_relative_to_buffer: buffering
expandable: true
importable_attributes:
- fixed_operation_and_maintenance_costs_per_year
- full_load_hours
- initial_investment
- input_capacity
- storage.volume
- technical_lifetime
- variable_operation_and_maintenance_costs_for_ccs_per_full_load_hour
- variable_operation_and_maintenance_costs_per_full_load_hour
