---
name: Electric car
export_to: transport_car_using_electricity_share
carrier: electricity
behavior: electric_vehicle
visible: true
composite: false
default_capacity: 3.7
default_volume: 25.0
default_demand: 
default_position_relative_to_buffer: 
expandable: true
importable_attributes:
- fixed_operation_and_maintenance_costs_per_year
- full_load_hours
- initial_investment
- input_capacity
- storage.volume
- technical_lifetime
- variable_operation_and_maintenance_costs_for_ccs_per_full_load_hour
- variable_operation_and_maintenance_costs_per_full_load_hour
